### ISSUE TITLE
Test case that uses source code of `chasten` fails in development branch

### ISSUE THREAD

**Issue by simojo** [AstuteSource/chasten#59]
**Describe the bug**
When on a development branch, after having made some changes to the source code, I was running tests and realized that chasten is being called to analyze itself:

`chasten analyze testing --search-path /path/to/chasten/repo --config /path/to/chasten/repo/.chasten --verbose`

The problem with this is that chasten is using a hard-coded config located in the `.chasten` directory, and because chasten's code changes, these checks will not always pass.

```
.chasten
├── checks.yml
└── config.yml
```

This hard-coded config was being read by the test case `tests/test_main.py::test_cli_analyze_correct_arguments_analyze_chasten_codebase`. _Chasten is essentially shooting itself in the foot_, and will not pass test cases when significant changes are made to it that break the following checks:

```yaml
checks:
  - name: "class-definition"
    code: "CDF"
    id: "C001"
    pattern: './/ClassDef'
    count:
      min: 1
      max: 50
  - name: "all-function-definition"
    code: "AFD"
    id: "F001"
    pattern: './/FunctionDef'
    count:
      min: 1
      max: 200
  - name: "non-test-function-definition"
    code: "NTF"
    id: "F002"
    pattern: './/FunctionDef'
    count:
      min: 40
      max: 70
  - name: "single-nested-if"
    code: "SNI"
    id: "CL001"
    pattern: './/FunctionDef/body//If'
    count:
      min: 1
      max: 100
  - name: "double-nested-if"
    code: "DNI"
    id: "CL002"
    pattern: './/FunctionDef/body//If'
    count:
      min: 1
      max: 15
```

In my case, you can read the output below to see that the `non-test-function-definition` and `double-nested-if` patterns were not being found. There is no need to enforce these arbitrary checks on our code.

```
✨ Analyzing Python source code in: /_scratch/chasten

🎉 Performing 5 check(s):

  ✓ id: 'C001', name: 'class-definition', pattern: './/ClassDef', min=1, max=50
    • /_scratch/chasten/chasten/constants.py - 10 matches
    • /_scratch/chasten/chasten/debug.py - 2 matches
    • /_scratch/chasten/chasten/enumerations.py - 3 matches
    • /_scratch/chasten/chasten/results.py - 6 matches
    • /_scratch/chasten/chasten/server.py - 1 matches
  ✓ id: 'F001', name: 'all-function-definition', pattern: './/FunctionDef', min=1, max=200
    • /_scratch/chasten/chasten/filesystem.py - 12 matches
    • /_scratch/chasten/chasten/validate.py - 4 matches
    • /_scratch/chasten/chasten/util.py - 5 matches
    • /_scratch/chasten/chasten/main.py - 9 matches
    • /_scratch/chasten/chasten/configuration.py - 10 matches
    • /_scratch/chasten/chasten/output.py - 12 matches
    • /_scratch/chasten/chasten/checks.py - 9 matches
    • /_scratch/chasten/chasten/database.py - 5 matches
    • /_scratch/chasten/chasten/server.py - 2 matches
    • /_scratch/chasten/chasten/process.py - 4 matches
    • /_scratch/chasten/tests/test_debug.py - 8 matches
    • /_scratch/chasten/tests/test_validate.py - 4 matches
    • /_scratch/chasten/tests/test_filesystem.py - 16 matches
    • /_scratch/chasten/tests/test_configuration.py - 3 matches
    • /_scratch/chasten/tests/test_main.py - 10 matches
    • /_scratch/chasten/tests/test_util.py - 4 matches
    • /_scratch/chasten/tests/test_constants.py - 5 matches
    • /_scratch/chasten/tests/test_process.py - 3 matches
    • /_scratch/chasten/tests/test_checks.py - 8 matches
  ✗ id: 'F002', name: 'non-test-function-definition', pattern: './/FunctionDef[not(contains(@name, "test_"))]', min=40,
max=70
    • /_scratch/chasten/chasten/filesystem.py - 12 matches
    • /_scratch/chasten/chasten/validate.py - 4 matches
    • /_scratch/chasten/chasten/util.py - 5 matches
    • /_scratch/chasten/chasten/main.py - 9 matches
    • /_scratch/chasten/chasten/configuration.py - 10 matches
    • /_scratch/chasten/chasten/output.py - 10 matches
    • /_scratch/chasten/chasten/checks.py - 9 matches
    • /_scratch/chasten/chasten/database.py - 5 matches
    • /_scratch/chasten/chasten/server.py - 2 matches
    • /_scratch/chasten/chasten/process.py - 4 matches
    • /_scratch/chasten/tests/test_main.py - 1 matches
  ✓ id: 'CL001', name: 'single-nested-if', pattern: './/FunctionDef/body//If', min=1, max=100
    • /_scratch/chasten/chasten/filesystem.py - 11 matches
    • /_scratch/chasten/chasten/validate.py - 3 matches
    • /_scratch/chasten/chasten/util.py - 2 matches
    • /_scratch/chasten/chasten/main.py - 15 matches
    • /_scratch/chasten/chasten/configuration.py - 14 matches
    • /_scratch/chasten/chasten/output.py - 7 matches
    • /_scratch/chasten/chasten/checks.py - 13 matches
    • /_scratch/chasten/chasten/database.py - 11 matches
    • /_scratch/chasten/chasten/process.py - 5 matches
    • /_scratch/chasten/tests/test_filesystem.py - 1 matches
    • /_scratch/chasten/tests/test_util.py - 1 matches
    • /_scratch/chasten/tests/test_constants.py - 1 matches
    • /_scratch/chasten/tests/test_process.py - 1 matches
    • /_scratch/chasten/tests/test_checks.py - 1 matches
  ✗ id: 'CL002', name: 'double-nested-if', pattern: './/FunctionDef/body//If[ancestor::If and not(parent::orelse)]', min=1,
max=15
    • /_scratch/chasten/chasten/filesystem.py - 3 matches
    • /_scratch/chasten/chasten/validate.py - 1 matches
    • /_scratch/chasten/chasten/main.py - 2 matches
    • /_scratch/chasten/chasten/configuration.py - 2 matches
    • /_scratch/chasten/chasten/output.py - 1 matches
    • /_scratch/chasten/chasten/checks.py - 3 matches
    • /_scratch/chasten/chasten/database.py - 4 matches
```

**To Reproduce**
1. In chasten repo: `git checkout e264ae97c4dfa3f408695158bc7fb867ea2cd769`
2. `poetry lock; poetry install`
3. `poetry run task test-not-randomly` (this ensures no other failed test cases clutter up the output)
4. Previously mentioned test case will fail: `tests/test_main.py:118 test_cli_analyze_correct_arguments_analyze_chasten_codebase`

**Expected behavior**
This test case should pass.

**Desktop (please complete the following information):**
 - OS: NixOS 22.11.2301.cff83d5032a

**Proposed Solution**

We simply need to remove this hard coded config and rely on something more static, such as a small sample python program located in `tests` that has code that will never change rather than analyzing our own codebase.

This is very meta that we are learning how our tool works because we're using our tool to analyze our tool, isn't it?
